name: CI
on: [push]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [14] # Version of GFortran we want to use.
        python-version: [3.12]
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}
      
    steps:
    - name: Install GFortran Linux
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y gfortran
        sudo apt-get install libblas-dev liblapack-dev
        
    - name: build application
      run: make 
